name: DNSValidator

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at 12:00 AM UTC
  workflow_dispatch: # manual trigger

permissions:
  contents: write

jobs:
  dnsvalidator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install & Run Dnsvalidator
        run: python -m pip install git+https://github.com/vortexau/dnsvalidator.git
        
      - name: Generate Valid Resolvers
        run: dnsvalidator -tL https://raw.githubusercontent.com/proabiral/Fresh-Resolvers/master/resolvers.txt -threads 30 -o resolvers.txt

      - name: Clean Empty Lines
        run: sed -i '/^$/d' resolvers.txt
        
      - name: Commit & Push Valid Resolvers to Repository
        run: |
          git config --local user.name "resolversbot"
          git config --local user.email "resolvers@bot"
          git add resolvers.txt
          git diff --cached --quiet || git commit -m "updated valid resolvers"
          git push origin main --force
